# Generated by Django 4.2.5 on 2024-03-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', 'add_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_state',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
    ]
